from requests import *
import requests
import time
import random
import os
import webbrowser
import sys
from user_agent import *
webbrowser.open('')
Z = '\x1b[1;31m'
C = '\x1b[1;33m'
F = '\x1b[2;32m'
B = '\x1b[2;36m'
V = '\x1b[1;90m'
X = '\x1b[1;33m'
u = '1234567890'
G = "\033[1;97m"
Y = '\033[1;34m' 
A = '\033[2;34m'
W = "\033[1;97m"
lo = ('--')
k = 0
a = 0
logo = f'''

' .... NO! ...                  ... MNO! ...
   ..... MNO!! ...................... MNNOO! ...
 ..... MMNO! ......................... MNNOO!! .
.... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .
 ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....
    ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...
   ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....
   ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...  
    ....... MMMMM..    OPPMMP    .,OMI! ....
     ...... MMMM::   o.,OPMP,.o   ::I!! ...
         .... NNM:::.,,OOPM!P,.::::!! ....
          .. MMNNNNNOOOOPMO!!IIPPO!!O! .....
         ... MMMMMNNNNOO:!!:!!IPPPPOO! ....
           .. MMMMMNNOOMMNNIIIPPPOO!! ......
          ...... MMMONNMMNNNIIIOO!..........
       ....... MN MOMMMNNNIIIIIO! OO ..........
    ......... MNO! IiiiiiiiiiiiI OOOO ...........
  ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........
   .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........
   ...... MNNNNO! .. PPPPPPPPP .. MMNON!........
      ...... OO! ................. ON! .......
         ................................ 


    {Z} ----------------------------------
    {Z}﴾{F}${Z}﴿{W} ᴅᴇᴠᴇʟᴏᴘᴇʀ{Z}➣ {W} avsnr  
    {Z}﴾{X}${Z}﴿{W} ᴄʜᴀɴɴᴇʟ{Z}➣ {W} {W}@avsnr 
    {Z} ---------------------------------'''
print(logo) 
took = input(f'''{B}     ↻ ɪɴᴛᴇʀ ᴛᴏᴋᴇɴ ʙᴏᴛ  ⇨ {Z}''')
idddd = input(f'''{B}    ↻ ɪɴᴛᴇʀ ᴛᴇʟᴇɢʀᴀᴍ ɪᴅ  ⇨ {Z}''')
start_msg = requests.post(f"https://api.telegram.org/bot{took}/sendMessage?chat_id={idddd}&text= welcome ⁿʳ ⚜️❤️ ‌").json()
id_msg =(start_msg['result']["message_id"])
num = "0123456789"
Dom = input("      ɪɴᴛᴇʀ ᴅᴏᴍᴇɴ ⇨ ");print("            ="*25)
while True:api=get("https://randomuser.me/api?nat=US").text.split('email":"')[1].split('",')[0].split('@')[0]+Dom;open("Email.txt","a").write(api+"\n");print(api)

